DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/course/urls.py
from django.urls import path,re_path
from .views import CourseListView,CourseDetailView,CourseInfoView,CommentsView,AddCommentsView,VideoPlayView

# 写app的名字
app_name = 'course'

urlpatterns = [
    path('list/',CourseListView.as_view(),name='course_list'),
    re_path('course/(?P<course_id>\d+)/',CourseDetailView.as_view(),name='course_detail'),
    re_path('info/(?P<course_id>\d+)/',CourseInfoView.as_view(),name='course_info'),
    # 课程评论
    re_path('comment/(?P<course_id>\d+)/',CommentsView.as_view(),name='course_comments'),
    #添加评论
    path('add_comment/', AddCommentsView.as_view(), name="add_comment"),
    # 课程视频播放页
    re_path('video/(?P<video_id>\d+)/', VideoPlayView.as_view(), name="video_play"),
]

apps/organization/urls.py
from organization.views import AddFavView,OrgView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,TeacherListView,TeacherDetailView
from django.urls import path,re_path


# 要写上app的名字
app_name = 'organization'

urlpatterns = [
    path('list/',OrgView.as_view(),name='org_list'),
    path('add_ask/',AddUserAskView.as_view(),name='add_ask'),
    re_path('home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name="org_home"),   # 机构首页
    re_path('course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name="org_course"), # 机构课程
    re_path('desc/(?P<org_id>\d+)/',OrgDescView.as_view(),name='org_desc'),  # 机构介绍
    re_path('teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name="org_teacher"), # 机构讲师
    path('add_fav/', AddFavView.as_view(),name='add_fav'),
    # 讲师列表
    re_path('teacher/list/', TeacherListView.as_view(), name="teacher_list"),
    # 讲师详情
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name="teacher_detail"),

]

ldOnline/urls.py
import xadmin
from django.urls import path,include,re_path
from django.views.static import serve
from ldOnline.settings import MEDIA_ROOT
from django.views.generic import TemplateView
from users.views import LoginView,RegisterView,ActiveUserView,ForgetPwdView,ResetView,ModifyPwdView,LogoutView,LoginUnsafeView,IndexView
from organization.views import OrgView
from ldOnline.settings import STATIC_ROOT
urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    # 处理图片显示的url，使用django自带的server，传入参数告诉他去哪个路径找，我们有配置好的路径MEDIAROOT
    path('media/<path:path>',serve,{'document_root':MEDIA_ROOT}),# 静态文件
    path('ueditor/',include("DjangoUeditor.urls")),
    path('captcha/',include('captcha.urls')),


    # path('',TemplateView.as_view(template_name='index.html'),name='index'),# 首页
    path('',IndexView.as_view(),name='index'),# 首页
    path('login/',LoginView.as_view(),name='login'),# 登录
    path('logout/', LogoutView.as_view(), name="logout"),# 退出登录
    path('register/',RegisterView.as_view(),name='register'),#注册
    re_path("active/(?P<active_code>.*)/",ActiveUserView.as_view(),name='user_active'),#激活用户
    path('forget/',ForgetPwdView.as_view(),name='forget_pwd'),# 忘记密码
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name='reset_pwd'),# 修改密码get方式的提交地址
    path('modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),# 修改密码post方式的提交地址

    path('users/',include('users.urls',namespace='users')),
    path("org/",include('organization.urls',namespace='org')),
    path('course/',include('course.urls',namespace='course')),


    # 全文配置404和500
    re_path(r'^static/?P<path>.*',serve,{'document_root':STATIC_ROOT}),

    re_path('^login/', LoginUnsafeView.as_view(), name='login')


]

# 全局404页面配置
handler404 = 'users.views.pag_not_found'

# 全局500页面配置
handler500 = 'users.views.page_error'

apps/course/models.py
from django.db import models
from datetime import datetime
from organization.models import CourseOrg
from organization.models import Teacher
from DjangoUeditor.models import UEditorField


# Course 课程
class Course(models.Model):
    DEGREE_CHOICES = (
        ('cj','初级'),
        ('zj','中级'),
        ('gj','高级')
    )

    name = models.CharField(max_length=50,verbose_name='课程名')
    desc = models.CharField(max_length=300,verbose_name='课程描述')
    detail = UEditorField(width=600,height=300,imagePath="courses/ueditor/",filePath="courses/ueidtor/",default='',verbose_name='课程详情')
    degree = models.CharField(choices=DEGREE_CHOICES,max_length=2,verbose_name='难度')
    learn_times = models.IntegerField(default=0,verbose_name='学习时长(分钟数)')
    students = models.IntegerField(default=0,verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0,verbose_name='收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m',max_length=100,verbose_name='封面图')
    click_nums = models.IntegerField(default=0,verbose_name='点击数')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')
    course_org = models.ForeignKey(CourseOrg,on_delete=models.CASCADE,verbose_name='所属机构',null=True,blank=True)
    category = models.CharField(max_length=20,default='',verbose_name='课程类别')
    tag = models.CharField(default='',max_length=10,verbose_name='课程标签')
    teacher = models.ForeignKey(Teacher, null=True, blank=True, on_delete=models.CASCADE,verbose_name='讲师')
    youneed_know = models.CharField( max_length=300, default='',verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=300, default='',verbose_name='老师告诉你')
    is_banner = models.BooleanField(default=False,verbose_name='是否轮播')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def get_zj_nums(self):
        # 获取课程的章节数
        # 获取课程的章节数
        return self.lesson_set.all().count()
    get_zj_nums.short_description = '章节数'  # 在后台显示的名称

    def get_course_lesson(self):
        # 获取课程的章节
        return self.lesson_set.all()

    def get_learn_users(self):
        # 获取这门课程的学习用户
        return self.usercourse_set.all()[:5]

    # def go_to(self):
    #     from django.utils.safestring import mark_safe
    #     # mark_safe后就不会转义
    #     return mark_safe("<a href='https://home.cnblogs.com/u/derek1184405959/'>跳转</a>")
    # go_to.short_description = "跳转"


    def __str__(self):
        return self.name


# Lesson 章节信息表
class Lesson(models.Model):
    course = models.ForeignKey(Course,verbose_name='课程',on_delete=models.CASCADE)
    name = models.CharField(max_length=100,verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def get_lesson_vedio(self):
        # 获取章节所有视频
        return self.video_set.all()

    def __str__(self):
        return '《{0}》课程的章节 >> {1}'.format(self.course,self.name)


# Video 视频
class Video(models.Model):
    lesson = models.ForeignKey(Lesson,verbose_name='章节',on_delete=models.CASCADE)
    name = models.CharField(max_length=100,verbose_name='视频名')
    url = models.CharField(default='',max_length=200,verbose_name='访问地址')
    learn_times = models.IntegerField(default=0,verbose_name='学习时长(分钟数)')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# CourseResource 课程资源
class CourseResource(models.Model):
    course = models.ForeignKey(Course,verbose_name='课程',on_delete=models.CASCADE)
    name = models.CharField(max_length=100,verbose_name='名称')
    download = models.FileField(upload_to='course/resource/%Y/%m',max_length=100,verbose_name='资源文件')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')

    class Meta:
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name



class BannerCourse(Course):
    '''显示轮播课程'''
    class Meta:
        verbose_name = '轮播课程'
        verbose_name_plural = verbose_name
        #这里必须设置proxy=True，这样就不会再生成一张表，同时还具有Model的功能
        proxy = True

apps/course/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from django.db.models import Q
from .models import Course,CourseResource,Video
from operation.models import UserFavorite,CourseComments,UserCourse
from pure_pagination import PageNotAnInteger,Paginator,EmptyPage
from utils.mixin_utils import LoginRequiredMixin
# Create your views here.


class CourseListView(View):
    '''课程列表'''
    def get(self, request):
        all_courses = Course.objects.all().order_by('-add_time')
        # 热门课程推荐
        hot_courses = Course.objects.all().order_by('-click_nums')[:3]
        # 搜索功能
        search_keywords = request.GET.get('keywords', '')
        if search_keywords:
            # 在name字段进行操作,做like语句的操作。i代表不区分大小写
            # or操作使用Q
            all_courses = all_courses.filter(Q(name__icontains=search_keywords) | Q(desc__icontains=search_keywords) | Q(
                detail__icontains=search_keywords))
        # 排序
        sort = request.GET.get('sort', "")
        if sort:
            if sort == "students":
                all_courses = all_courses.order_by("-students")
            elif sort == "hot":
                all_courses = all_courses.order_by("-click_nums")
        # 分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_courses,2 , request=request)
        courses = p.page(page)
        return render(request, "course/course-list.html", {
            "all_courses":courses,
            'sort': sort,
            'hot_courses':hot_courses,

        })


class CourseDetailView(View):
    '''课程详情'''
    def get(self,request,course_id):
        course = Course.objects.get(id=int(course_id))
        # 课程的点击数加1
        course.click_nums += 1
        course.save()
        # 课程标签
        # 通过当前标签，查找数据库中的课程
        has_fav_course = False
        has_fav_org = False

        # 必须是用户已登录我们才需要判断
        if request.user.is_authenticated:
            if UserFavorite.objects.filter(user=request.user,fav_id=course.id,fav_type=1):
                has_fav_course = True
            if UserFavorite.objects.filter(user=request.user,fav_id=course.course_org.id,fav_type=2):
                has_fav_org = True
        tag = course.tag
        if tag:
            # 需要从1开始不然会推荐自己
            relate_courses = Course.objects.filter(tag=tag)[:3]
        else:
            relate_courses = []
        return render(request,'course/course-detail.html',{
            'course':course,
            'relate_courses':relate_courses,
            'has_fav_course':has_fav_course,
            'has_fav_org':has_fav_org,
        })


class CourseInfoView(LoginRequiredMixin,View):
    '''课程章节信息'''
    def get(self,request,course_id):
        course = Course.objects.get(id=int(course_id))

        # 查询用户是否已经学习了该课程
        user_courses = UserCourse.objects.filter(user=request.user, course=course)
        if not user_courses:
            # 如果没有学习该门课程就关联起来
            user_course = UserCourse(user=request.user, course=course)
            user_course.save()

        #相关课程推荐
        # 找到学习这门课的所有用户
        user_courses = UserCourse.objects.filter(course=course)
        # 找到学习这门课的所有用户的id
        user_ids = [user_course.user_id for user_course in user_courses]
        # 通过所有用户的id,找到所有用户学习过的所有过程
        all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)
        # 取出所有课程id
        course_ids = [all_user_course.course_id for all_user_course in all_user_courses]
        # 通过所有课程的id,找到所有的课程，按点击量去五个
        relate_courses = Course.objects.filter(id__in=course_ids).order_by("-click_nums")[:5]

        course.students += 1
        course.save()

        # 资源
        all_resources = CourseResource.objects.filter(course=course)
        return render(request,'course/course-video.html',{
            'course':course,
            'all_resources':all_resources,
            'relate_courses':relate_courses,
        })


class CommentsView(LoginRequiredMixin,View):
    '''课程评论'''
    def get(self,request,course_id):
        course = Course.objects.get(id=int(course_id))
        all_resources = CourseResource.objects.filter(course=course)
        all_comments = CourseComments.objects.all()
        return render(request,'course/course-comment.html',{
            'course':course,
            'all_resources':all_resources,
            'all_comments':all_comments,
        })


class AddCommentsView(View):
    '''用户评论'''
    def post(self,request):
        if not request.user.is_authenticated:
            # 未登录时返回json提示未登录，跳转到登陆页面是在ajax中做的
            return HttpResponse('{"status":"fail","msg":"用户未登录"}',content_type='application/json')
        course_id = request.POST.get('course_id',0)
        comments = request.POST.get('comments','')
        if int(course_id) > 0 and comments:
            # 实例化一个course_comments对象
            course_comments = CourseComments()
            # 获取评论的是哪门课程
            course = Course.objects.get(id=int(course_id))
            # 分别把评论的课程，评论的内容和评论的用户保存到数据库
            course_comments.course = course
            course_comments.comments = comments
            course_comments.user = request.user
            course_comments.save()
            return HttpResponse('{"status":"success","msg":"评论成功"}',content_type='application/json')
        else:
            return HttpResponse('{"status":"fail","msg":"评论失败"}',content_type='application/json')


class VideoPlayView(LoginRequiredMixin,View):
    '''课程章节视频播放页面'''
    def get(self,request,video_id):
        video = Video.objects.get(id=int(video_id))
        # 通过外键找到章节再找到视频对应的课程
        course = video.lesson.course
        course.students += 1
        course.save()

        # 查询用户是否已经学习了该课程
        user_courses = UserCourse.objects.filter(user=request.user,course=course)
        if not user_courses:
            # 如果没有学习该门课程就关联起来
            user_course = UserCourse(user=request.user,course=course)
            user_course.save()

            # 相关课程推荐
            # 找到学习这门课的所有用户
            user_courses = UserCourse.objects.filter(course=course)
            # 找到学习这门课的所有用户的id
            user_ids = [user_course.user_id for user_course in user_courses]
            # 通过所有用户的id,找到所有用户学习过的所有过程
            all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)
            # 取出所有课程id
            course_ids = [all_user_course.course_id for all_user_course in all_user_courses]
            # 通过所有课程的id,找到所有的课程，按点击量去五个
            relate_courses = Course.objects.filter(id__in=course_ids).order_by("-click_nums")[:5]

            # 资源
            all_resources = CourseResource.objects.filter(course=course)
            return render(request, 'course/course-play.html', {
                'course': course,
                'all_resources': all_resources,
                'relate_courses': relate_courses,
                'video': video,
            })

templates/course/course-play.html
{% extends 'base.html' %}

{% block titile %}
    {{ video.name }} 在线网
{% endblock %}

{% load staticfiles %}
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="{% url 'index' %}">首页</a>></li>
                    <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'course:course_detail' course.id %}">{{ course.name }}</a>></li>
                    <li></li>
                </ul>
            </div>
        </div>
    </section>
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/video-js.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <style>
        .video-js .vjs-big-play-button {
            top: 50%;
            left: 50%;
        }
    </style>
{% endblock %}

{% block custom_js %}
    <script src="{% static 'js/video.min.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
    <div id="main">

        <div class="course-info-main clearfix w has-progress">
            <div style="width:1200px;height: 650px; margin-left:100px">
                <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="1200"
                       poster="http://video-js.zencoder.com/oceans-clip.png"
                       data-setup="" type="video/mp4">
                    <source src="{{ video.url }}">
                </video>
            </div>
            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active active" id="learnOn"
                                       href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class=""
                                       href="{% url 'course:course_comments' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>
                        <div id="notice" class="clearfix">
                            <div class="l"><strong>课程公告:</strong> <a
                                    href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a></div>
                        </div>

                        <div class="mod-chapters">
                            {% for lesson in course.lesson_set.get_queryset %}
                                <div class="chapter chapter-active">
                                    <h3>
                                        <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                                    </h3>
                                    <ul class="video">

                                        {% for video in lesson.video_set.get_queryset %}
                                            <li>
                                                <a target="_blank" href='{% url 'course:video_play' video.id %}'
                                                   class="J-media-item studyvideo">{{ video.name }}
                                                    ({{ video.learn_times }})
                                                    <i class="study-state"></i>
                                                </a>
                                            </li>
                                        {% endfor %}

                                    </ul>
                                </div>
                            {% endfor %}
                        </div>

                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                                <h4>资料下载</h4>
                                <ul class="downlist">
                                    {% for course_resource in course.courseresource_set.get_queryset %}
                                        <li>
                                            <span><i
                                                    class="aui-iconfont aui-icon-file"></i>  {{ course_resource.name }}</span>
                                            <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode"
                                               target="_blank" download="" data-id="274" title="">下载</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="box mb40">
                                <h4>讲师提示</h4>
                                <div class="teacher-info">
                                    <a href="{% url 'org:teacher_detail' course.teacher.id %}" target="_blank">
                                        <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80'/>
                                    </a>
                                    <span class="tit">
          <a href="{% url 'org:teacher_detail' course.teacher.id %}" target="_blank">{{ course.teacher.name }}</a>
        </span>
                                    <span class="job">{{ course.teacher.work_position }}</span>
                                </div>
                                <div class="course-info-tip">
                                    <dl class="first">
                                        <dt>课程须知</dt>
                                        <dd class="autowrap">{{ course.you_need_know }}</dd>
                                    </dl>
                                    <dl>
                                        <dt>老师告诉你能学到什么？</dt>
                                        <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                    </dl>
                                </div>
                            </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course"
                                         style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">

                                            {% for relate_course in relate_courses %}
                                                <li class="curr">
                                                    <a href="{% url 'course:course_detail' relate_course.id %}"
                                                       target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ relate_course.image }}"
                                                             alt="{{ relate_course.name }}">
                                                        <span class="name autowrap">{{ relate_course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}

                                        </ul>
                                    </div>
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                        <ul class="other-list">

                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="clear"></div>

            </div>

        </div>
    </div>
{% endblock %}

templates/course/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}课程列表{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
        <div class="crumbs">
            <ul>
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                <li><a href="{% url 'course:course_detail' course.id %}">公开课程</a>></li>
                <li>课程详情</li>
            </ul>
        </div>
    </div>
    </section>
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aui.css' %}" />
{% endblock %}

{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_times }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'course:course_comments' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">Spring的文档以及相关的jar文件已上传</a> </div>
                </div>

                <div class="mod-chapters">
                    {% for lesson in course.get_course_lesson %}
                    <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for vedio in lesson.get_lesson_vedio %}
                            <li>
                                <a target="_blank" href='{{ vedio.url }}' class="J-media-item studyvideo">{{ vedio.name }}{{ vedio.learn_times }}
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for course_resource in all_resources %}
                            <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>  {{ course_resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ course_resource.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for relate_course in relate_courses %}
                                    <li class="curr">
                                        <a href="{% url 'course:course_detail' relate_course.id %}course-detail.html" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name }}">
                                            <span class="name autowrap">{{ relate_course.name }}</span>
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
</div>
{% endblock %}